services:
    dizda.cloudbackup.chain.database:
        class: Dizda\CloudBackupBundle\Chain\DatabaseChain

    dizda.cloudbackup.chain.client:
        class: Dizda\CloudBackupBundle\Chain\ClientChain

    dizda.cloudbackup.client.cloudapp:
        class: Dizda\CloudBackupBundle\Clients\CloudAppClient
        arguments:
            - %dizda_cloud_backup.cloud_storages%
        tags:
            -  { name: dizda.cloudbackup.client }

    dizda.cloudbackup.client.dropbox:
        class: Dizda\CloudBackupBundle\Clients\DropboxClient
        arguments:
            - %dizda_cloud_backup.cloud_storages%
        tags:
            -  { name: dizda.cloudbackup.client }

    dizda.cloudbackup.client.google_drive:
        class: Dizda\CloudBackupBundle\Clients\GoogleDriveClient
        public: false
        arguments: [~, ~, ~]
        tags:
            -  { name: dizda.cloudbackup.client }

    dizda.cloudbackup.client.gaufrette:
        class: Dizda\CloudBackupBundle\Clients\GaufretteClient
        tags:
            -  { name: dizda.cloudbackup.client }

    dizda.cloudbackup.database.mongodb:
        class: Dizda\CloudBackupBundle\Databases\MongoDB
        arguments:
            - %dizda_cloud_backup.databases%
            - %dizda_cloud_backup.output_folder%
        calls:
            - [ setTimeout, [ %dizda_cloud_backup.timeout% ] ]
        tags:
            -  { name: dizda.cloudbackup.database }

    dizda.cloudbackup.database.mysql:
        class: Dizda\CloudBackupBundle\Databases\MySQL
        arguments:
            - %dizda_cloud_backup.databases%
            - %dizda_cloud_backup.output_folder%
        calls:
            - [ setTimeout, [ %dizda_cloud_backup.timeout% ] ]
        tags:
            -  { name: dizda.cloudbackup.database }

    dizda.cloudbackup.database.postgresql:
        class: Dizda\CloudBackupBundle\Databases\PostgreSQL
        arguments:
            - %dizda_cloud_backup.databases%
            - %dizda_cloud_backup.output_folder%
        calls:
            - [ setTimeout, [ %dizda_cloud_backup.timeout% ] ]
        tags:
            -  { name: dizda.cloudbackup.database }

    dizda.cloudbackup.processor.tar:
        class: Dizda\CloudBackupBundle\Processors\TarProcessor
        arguments: 
            - %dizda_cloud_backup.root_folder%
            - %dizda_cloud_backup.output_folder%
            - %dizda_cloud_backup.output_file_prefix%
            - %dizda_cloud_backup.folders%
            - %dizda_cloud_backup.processor%

    dizda.cloudbackup.processor.zip:
        class: Dizda\CloudBackupBundle\Processors\ZipProcessor
        arguments: 
            - %dizda_cloud_backup.root_folder%
            - %dizda_cloud_backup.output_folder%
            - %dizda_cloud_backup.output_file_prefix%
            - %dizda_cloud_backup.folders%            
            - %dizda_cloud_backup.processor%

    dizda.cloudbackup.processor.7z:
        class: Dizda\CloudBackupBundle\Processors\SevenZipProcessor
        arguments: 
            - %dizda_cloud_backup.root_folder%
            - %dizda_cloud_backup.output_folder%
            - %dizda_cloud_backup.output_file_prefix%
            - %dizda_cloud_backup.folders%            
            - %dizda_cloud_backup.processor%

    # Managers
    dizda.cloudbackup.manager.backup:
        class: Dizda\CloudBackupBundle\Manager\BackupManager
        arguments:
            - @logger
            - @dizda.cloudbackup.chain.database
            - @dizda.cloudbackup.chain.client
            - @dizda.cloudbackup.service.mailer

    # Services
    dizda.cloudbackup.service.mailer:
            class: Dizda\CloudBackupBundle\Service\Mailer
            arguments:
                - @mailer
                - %dizda_cloud_backup.error_notification%