services:
    dizda.cloudbackup.client.cloudapp:
        class: Dizda\CloudBackupBundle\Clients\CloudAppClient
        arguments:
            - %dizda_cloud_backup.cloud_storages%

    dizda.cloudbackup.client.dropbox:
        class: Dizda\CloudBackupBundle\Clients\DropboxClient
        arguments:
            - %dizda_cloud_backup.cloud_storages%

    dizda.cloudbackup.client.google_drive:
        class: Dizda\CloudBackupBundle\Clients\GoogleDriveClient
        public: false
        arguments: [~, ~, ~]

    dizda.cloudbackup.client.gaufrette:
        class: Dizda\CloudBackupBundle\Clients\GaufretteClient

    dizda.cloudbackup.database.mongodb:
        class: Dizda\CloudBackupBundle\Databases\MongoDB
        arguments:
            - %dizda_cloud_backup.databases%
            - %dizda_cloud_backup.output_folder%

    dizda.cloudbackup.database.mysql:
        class: Dizda\CloudBackupBundle\Databases\MySQL
        arguments:
            - %dizda_cloud_backup.databases%
            - %dizda_cloud_backup.output_folder%

    dizda.cloudbackup.database.postgresql:
        class: Dizda\CloudBackupBundle\Databases\PostgreSQL
        arguments:
            - %dizda_cloud_backup.databases%
            - %dizda_cloud_backup.output_folder%

    dizda.cloudbackup.processor.tar:
        class: Dizda\CloudBackupBundle\Processors\TarProcessor
        arguments: 
            - %dizda_cloud_backup.root_folder%
            - %dizda_cloud_backup.output_folder%
            - %dizda_cloud_backup.output_file_prefix%
            - %dizda_cloud_backup.folders%
            - %dizda_cloud_backup.processor%

    dizda.cloudbackup.processor.zip:
        class: Dizda\CloudBackupBundle\Processors\ZipProcessor
        arguments: 
            - %dizda_cloud_backup.root_folder%
            - %dizda_cloud_backup.output_folder%
            - %dizda_cloud_backup.output_file_prefix%
            - %dizda_cloud_backup.folders%            
            - %dizda_cloud_backup.processor%

    dizda.cloudbackup.processor.7z:
        class: Dizda\CloudBackupBundle\Processors\SevenZipProcessor
        arguments: 
            - %dizda_cloud_backup.root_folder%
            - %dizda_cloud_backup.output_folder%
            - %dizda_cloud_backup.output_file_prefix%
            - %dizda_cloud_backup.folders%            
            - %dizda_cloud_backup.processor%